services:
  db:
    image: postgres:13
    container_name: trade_db
    environment:
      POSTGRES_DB: trade_analysis
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./SQL:/docker-entrypoint-initdb.d

volumes:
  postgres_data: